#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use Getopt::Long;

sub usage {
  print "usage: $0 [-v] [-s <host>] [-p <port>] <msg> ...\n";
  exit(-1);
}

our $server="127.0.0.1";
our $port = 10000;
our $verbose;
our $help;
usage unless GetOptions("port=i"           => \$port,
                        "server=s"         => \$server,
                        "verbose+"         => \$verbose,
                        "help"             => \$help);
usage if $help;
usage unless $port;
usage unless @ARGV;
our $msg = join " ", @ARGV;
my $sock = IO::Socket::INET->new( PeerPort => $port, PeerAddr => $server, 
                                  Proto => "udp", ) or die "socket: $!\n";

print STDERR "[$server:$port] < $msg\n" if $verbose;
$sock->send($msg);
