#!/bin/sh
#
# proctab: process monitor
#
# chkconfig:   2345 26 89
# description: process monitor daemon

. /etc/rc.d/init.d/functions

start()
{
    echo -n $"Starting proctab: "
    daemon --pidfile=/var/run/proctab.pid /usr/bin/proctab -p /var/run/proctab.pid 
    touch /var/lock/subsys/proctab
    echo
}

stop()
{
    echo -n $"Shutting down proctab: "
    killproc -p /var/run/proctab.pid proctab
    rm -f /var/lock/subsys/proctab
    echo
}

[ -f /usr/bin/proctab ] || exit 0

# see how we were called
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  condrestart)
        [ -e /var/lock/subsys/proctab ] && (stop; start)
        ;;
  status)
        status -p /var/run/proctab.pid proctab
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart}"
        exit 1
esac

exit 0
