#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;

sub usage {
  print STDERR "usage: $0 [options]\n";
  print STDERR "options: --verbose\n";
  print STDERR "         --start-service\n";
  print STDERR "         --install-service\n";
  print STDERR "         --initsys <auto|systemd|debian|upstart|rhel6>\n";
  print STDERR "         --bindir <auto|dirname> (e.g. /usr/bin)\n";
  exit -1;
}

our $start = 0;
our $install = 0;
our $verbose = 0;
our $initsys = "auto";
our $bindir = "/usr/bin";
our $help = 0;

my %cfg;
$cfg{systemd}{enable} = "systemctl enable proctab";
$cfg{systemd}{start}  = "systemctl start proctab";
$cfg{systemd}{service}= "/lib/systemd/system/proctab.service";
$cfg{systemd}{mode}=    0644;

$cfg{rhel6}{enable}   = "/sbin/chkconfig --add proctab";
$cfg{rhel6}{start}    = "/etc/init.d/proctab start";
$cfg{rhel6}{service}  = "/etc/rc.d/init.d/proctab";
$cfg{rhel6}{mode}=    0755;

$cfg{upstart}{enable} = "/bin/true";
$cfg{upstart}{start}  = "/sbin/start proctab";
$cfg{upstart}{service}= "/etc/init/proctab.conf";
$cfg{upstart}{mode}=    0644;

$cfg{debian}{enable}  = "/usr/sbin/update-rc.d proctab defaults";
$cfg{debian}{start}   = "/usr/sbin/service proctab start";
$cfg{debian}{service} = "/etc/init.d/proctab";
$cfg{debian}{mode}=    0755;

usage unless GetOptions( "verbose+"          => \$verbose,
                         "bindir=s"          => \$bindir,
                         "initsys=s"         => \$initsys,
                         "start-service"     => \$start,
                         "install-service"   => \$install,
                         "help"              => \$help);
usage if $help;
usage unless ($install or $start);

die "This script needs to run as root. Exiting.\n" unless $> == 0;

sub guess_initsystem {
  my $target = readlink "/sbin/init";

  if ((-l "/sbin/init") and ($target =~ /systemd/)) { $initsys = "systemd"; }
  elsif (-f "/etc/redhat-release")                  { $initsys = "rhel6";   }
  elsif (-f "/etc/debian_version")                  { $initsys = "debian";  }
  elsif (-d "/usr/lib/upstart")                     { $initsys = "upstart"; }
  else { die "can't guess initsystem"; }
  print "Initsystem: $initsys\n" if $verbose;
}

sub install_service {
  my $cmd;
  local $/; # slurp mode

  open TEMPLATE, "<${initsys}" or die "can't open $initsys: $!";
  my $script = <TEMPLATE>;
  close TEMPLATE;

  my $output = $cfg{$initsys}{$service};
  open SCRIPT, ">$output" or die "can't open $output: $!\n";
  print SCRIPT $script;
  close SCRIPT;

  # enable the new service
  $cmd = $cfg{$initsys}{enable};
  print "$cmd\n";
  die "error enabling iniscript" if system $cmd;
}

sub start_service {
  my $cmd = $cfg{$initsys}{start};
  print "$cmd\n";
  die "error starting service" if system $cmd;
}

guess_initsystem if $initsys eq "auto";
install_service if $install;
start_service if $start;
