#define TOK_REPORT                          1
#define TOK_TO                              2
#define TOK_STR                             3
#define TOK_LISTEN                          4
#define TOK_ON                              5
#define TOK_JOB                             6
#define TOK_LCURLY                          7
#define TOK_RCURLY                          8
#define TOK_NAME                            9
#define TOK_CMD                            10
#define TOK_DIR                            11
#define TOK_OUT                            12
#define TOK_IN                             13
#define TOK_ERR                            14
#define TOK_USER                           15
#define TOK_ORDER                          16
#define TOK_ENV                            17
#define TOK_ULIMIT                         18
#define TOK_DISABLED                       19
#define TOK_WAIT                           20
#define TOK_ONCE                           21
#define TOK_NICE                           22
#define TOK_BOUNCE                         23
#define TOK_EVERY                          24
#define TOK_DEPENDS                        25
#define TOK_CPUSET                         26
#define TOK_QUOTEDSTR                      27
